FROM golang:1.26-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG SERVICE_PATH
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/service ./${SERVICE_PATH}

FROM alpine:3.22

RUN adduser -D -u 10001 appuser
RUN mkdir -p /var/lib/pulsestream/archive /app && chown -R appuser:appuser /var/lib/pulsestream /app

WORKDIR /app
COPY --from=build /out/service /app/service

USER appuser
ENTRYPOINT ["/app/service"]
